"""Cross-implementation tests against @openzeppelin/merkle-tree.

The vectors in reference/vectors.json are generated by the original JS library
(see reference/README.md). Here we rebuild each tree with murky-tree and assert
we reproduce the JS root, flat tree, proofs, and multiproofs -- an independent
source of truth the self-referential unit tests can't provide. We also assert
the JSON round-trips in the exact (camelCase) format the JS library emits.
"""

import json
from pathlib import Path

import pytest
from eth_abi.grammar import parse
from eth_utils import to_bytes, to_hex

from murky_tree import SimpleMerkleTree, StandardMerkleTree
from murky_tree.utils import keccak

VECTORS_PATH = Path(__file__).resolve().parent.parent / "reference" / "vectors.json"


def load_cases():
    data = json.loads(VECTORS_PATH.read_text())
    return data["cases"]


CASES = load_cases()
CASE_IDS = [c["name"] for c in CASES]


# Must match reference/generate.ts's customNodeHash and tests/test_simple.py:
# double-hash the sorted pair (commutative).
def custom_node_hash(a: bytes, b: bytes) -> bytes:
    lo, hi = (a, b) if a < b else (b, a)
    return keccak(keccak(lo + hi))


def _coerce(value, abi_type):
    """Recursively coerce a JSON-safe vector value to eth-abi input form.

    Independent walk of the ABI type grammar (arrays, tuples/structs, ints at
    any depth) -- a deliberate re-implementation so this cross-check doesn't lean
    on the library's own transform. Integers arrive as decimal strings (JSON has
    no bigint) and become Python ints; bytes arrive as hex strings.
    """
    node = parse(abi_type) if isinstance(abi_type, str) else abi_type
    if node.is_array:
        return [_coerce(v, node.item_type) for v in value]
    components = getattr(node, "components", None)
    if components is not None:
        return [_coerce(v, c) for v, c in zip(value, components, strict=True)]
    if node.base in ("uint", "int"):
        return int(value)
    if node.base == "bytes" and isinstance(value, str):
        return to_bytes(hexstr=value)
    return value  # address, string, bool, ...


def coerce_standard_value(value: list, leaf_encoding: list[str]) -> list:
    return [_coerce(v, t) for v, t in zip(value, leaf_encoding, strict=True)]


def vector_leaf_hash(tree, case: dict, leaf) -> str:
    "leaf_hash of a raw vector leaf, coercing standard values first."
    if case["type"] == "standard":
        leaf = coerce_standard_value(leaf, case["input"]["leafEncoding"])
    return tree.leaf_hash(leaf)


def build_tree(case: dict):
    inp = case["input"]
    if case["type"] == "standard":
        values = [coerce_standard_value(v, inp["leafEncoding"]) for v in inp["values"]]
        return StandardMerkleTree.of(values, inp["leafEncoding"], inp["sortLeaves"])

    node_hash = custom_node_hash if inp["nodeHash"] == "custom" else None
    return SimpleMerkleTree.of(inp["values"], inp["sortLeaves"], node_hash=node_hash)


@pytest.mark.parametrize("case", CASES, ids=CASE_IDS)
class TestReferenceVectors:
    def test_root(self, case):
        assert build_tree(case).root == case["root"]

    def test_flat_tree(self, case):
        "the flat binary-heap array must match the JS library byte-for-byte"
        tree = build_tree(case)
        assert [to_hex(node) for node in tree.tree] == case["tree"]

    def test_leaf_hashes(self, case):
        tree = build_tree(case)
        for i, expected in enumerate(case["leafHashes"]):
            assert tree.leaf_hash(tree.values[i].value) == expected

    def test_single_proofs(self, case):
        tree = build_tree(case)
        for i, expected in enumerate(case["proofs"]):
            assert tree.get_proof(i) == expected

    def test_multiproofs(self, case):
        tree = build_tree(case)
        for mp in case["multiProofs"]:
            got = tree.get_multi_proof(mp["indices"])
            assert got.proof == mp["proof"]
            assert got.proof_flags == mp["proofFlags"]
            # Leaves are returned in tree order, possibly reordered from the
            # requested indices. Compare by leaf hash to avoid str-vs-int noise
            # on standard uint values.
            assert [tree.leaf_hash(v) for v in got.leaves] == [
                vector_leaf_hash(tree, case, v) for v in mp["leaves"]
            ]

    def test_to_json_matches_oz_dump(self, case):
        "murky-tree's JSON output is byte-for-byte the OZ format (as parsed JSON)"
        tree = build_tree(case)
        assert json.loads(json.dumps(tree.to_json())) == case["dump"]

    def test_from_json_loads_oz_dump(self, case):
        "murky-tree can load the raw JS dump and reproduce the root"
        if case["type"] == "standard":
            loaded = StandardMerkleTree.from_json(case["dump"])
        else:
            node_hash = (
                custom_node_hash if case["input"]["nodeHash"] == "custom" else None
            )
            loaded = SimpleMerkleTree.from_json(case["dump"], node_hash=node_hash)
        assert loaded.root == case["root"]
